name: Testing
on: 
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs: 
  name: Test
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: '3.10' 
    cache: 'pip' # caching pip dependencies
  - name: Dependencies Installation
  - run: pip install -r requirements.txt
  - name: Running Tests
  - run: python test/main_test.py
